version: '2'
services:
  users:
    build: ./user
    image: gin_with_docker_training/user
    container_name: user
    depends_on:
      - db
    links:
      - db

  db:
    image: mysql:latest
    environment: 
      MYSQL_ROOT_PASSWORD: root
    container_name: db-training
    ports:
      - "5656:5656"
    volumes:
      - ./backup:/backup:rw